# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
languages:
  ko:
    languageCode: ko
    # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
    # contentDir: content/ko

# Set default language and subdirectory
defaultContentLanguage: ko
defaultContentLanguageInSubdir: true

# Uncomment the lines below to configure your website in a second language.
# zh:
#   languageCode: zh-Hans
#   contentDir: content/zh
#   title: Chinese website title...
#   params:
#     description: Site description in Chinese...
#   menu:
#     main:
#       - name: 传
#         url: '#about'
#         weight: 1
