defaultContentLanguage: ko
defaultContentLanguageInSubdir: true
languages:
  ko:
    contentDir: content/ko
    disabled: false
    languageCode: ko-KR
    languageDirection: ltr
    languageName: 한국어
    params:
      subtitle: 참고 자료, 튜토리얼 및 설명
    title: 프로젝트 문서
    weight: 1
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Reference, Tutorials, and Explanations
    title: Project Documentation
    weight: 2
